version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${VITE_PORT:-80}:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - ./backend/.env.example
    volumes:
      - ./backend/temp:/app/temp
    restart: unless-stopped

networks:
  default:
    driver: bridge